function out1 = time_min_vel(a0,sf)
%TIME_MIN_VEL
%    OUT1 = TIME_MIN_VEL(A0,SF)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    27-Nov-2024 16:44:22

out1 = -(sqrt(1.5e+1).*sqrt(-a0.*sf))./a0;
end
